### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#827] opened 2023-10-15 02:35 UTC
On the homepage I'm getting this warning:
`Deprecated: parse_str(): Passing null to parameter #1 ($string) of type string is deprecated in /app/web/wp-content/themes/lfevents/library/cleanup.php on line 123`

**Comment by thetwopct** [comment] 2023-10-24 07:29
Closing as duplicate of #834 (already committed against that issue)

**Closed by thetwopct** 2023-10-24 07:29 UTC
