### ISSUE TITLE
Programmatically deal with past events

### ISSUE THREAD

**Issue by dankohn** [LF-Engineering/lfevents#485] opened 2020-02-13 20:49 UTC
https://events.linuxfoundation.org/chisel-community-conference/ has passed but the Register button is still on it. Can we set the button to automatically disappear when the event has fully passed.

Also, can we automatically add a banner saying either "This event has passed. Please visit the current [KubeCon + CloudNativeCon] event." if there is a new one. If not, can we say "This event has passed. Please visit other [Open Source Summit] events." And if there are no upcoming events in the same category, can we just say "Please visit other upcoming Linux Foundation events."

@meganelizabethphillips Does this all sound OK to you?

**Comment by meganelizabethphillips** [comment] 2020-02-13 22:20
Hey Dan!

I like the banner idea to close out the event. As far as automating the
register button, I would prefer to leave as is as I manually need to pull
several buttons post event. I'll make a note to include this as part of our
process moving forward.

Thanks!

Megan Phillips, PMP
Events Web Project Manager
The Linux Foundation
1 Letterman Drive
Building D, Suite D4700
San Francisco, CA 94129
E: mphillips@linuxfoundation.org



Why Attend Linux Foundation Events <https://youtu.be/X_rLxfmLlYY>
Why Sponsor Linux Foundation Events <https://youtu.be/Rr-9cIH42fE>


_______________
*Upcoming Out of Office*
President's Day: February 17 (no email access)
Limited Hours: February 19 & February 25 (limited email access)

**Comment by dankohn** [comment] 2020-02-13 22:36
OK, but you might want to consider having the buttons automatically updated, the same way we're discussing with https://github.com/LF-Engineering/lfevents/issues/478

**Comment by meganelizabethphillips** [comment] 2020-02-13 22:38
I'm having a hard time conceptualizing how we would automate the buttons on
various pages with various uses. If I could see an example this would be
helpful.

Megan Phillips, PMP
Events Web Project Manager
The Linux Foundation
1 Letterman Drive
Building D, Suite D4700
San Francisco, CA 94129
E: mphillips@linuxfoundation.org



Why Attend Linux Foundation Events <https://youtu.be/X_rLxfmLlYY>
Why Sponsor Linux Foundation Events <https://youtu.be/Rr-9cIH42fE>


_______________
*Upcoming Out of Office*
President's Day: February 17 (no email access)
Limited Hours: February 19 & February 25 (limited email access)

**Comment by cjyabraham** [comment] 2020-02-27 13:31
I've split off the banner idea to #501.  It sounds like Megan wants to keep the manual control over the CTA buttons on the event itself, so I'll close out this issue.

**Comment by cjyabraham** [comment] 2020-02-27 17:17
Reopening so we can revisit the idea of automating the CTA buttons later.

**Comment by cjyabraham** [comment] 2020-03-01 10:40
Some possible ideas for this:
1. Create a button block with an expiry date that makes it disappear after that date, similar to the new alert block.  One thing I don't like about this solution is that the "Register" button, for example, will have a date set that is a duplicate of the same date set for the Event Register CTA meta info.  So it'll be in two places and both would need to be updated if the date were to change.  I'm not sure if there's a way to inherit the expiry date from the parent Event but that should be investigated.
2. Create some kind of dashboard that lists Events with their various key dates that require update actions to remove buttons etc.  This way, at a glance, you can see which Events need some kind of action and then check them off as "done" once performed.

@meganelizabethphillips let's discuss whether any of the above would be helpful next time we talk.

**Comment by cjyabraham** [comment] 2020-03-05 02:35
Megan is in favor of pursuing option 1.

**Comment by cjyabraham** [comment] 2020-03-05 13:01
I've created a clean new issue on this for Diego, #511, so I'll close out this issue.

**Closed by cjyabraham** 2020-03-05 13:01 UTC
Labels: enhancement
